name: 'transform'
profile: 'e-commerce'
model-paths: ["models"]  
models:
  transform:
    staging:
      +materialized: view
      snowflake_warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"  # Models in `staging` will go to `staging` schema

    intermediate:
      +materialized: table
      snowflake_warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      +schema: intermediate  # Models in `intermediate` will go to `intermediate` schema


