name: 'transform'
profile: 'e-commerce'
model-paths: ["models"]  
models:
  transform:
    staging:
      +materialized: view
      snowflake_warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"  

    intermediate:
      +materialized: table
      snowflake_warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      +schema: intermediate

    analytics:
      +materialized: table
      snowflake_warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      +schema: analytics


