name: 'transform'

profile: 'e-commerce'

models:
  e-commerce:
    staging:
      +materialized: view 
      +schema: staging  
      snowflake_warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"

    intermediate:
      +materialized: table
      +schema: intermediate  
      snowflake_warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"

    analytics:
      +materialized: table
      +schema: marts
      snowflake_warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"